export const emojiGames = {
  movies: [
    { emoji: "🎥👨‍🎤", phrase: "A Star is Born", hint: "A tale of fame and heartbreak in the music industry." },
    { emoji: "🦁👑", phrase: "The Lion King", hint: "A coming-of-age story in the animal kingdom with a royal twist." },
    { emoji: "🚢💔", phrase: "Titanic", hint: "A historical romance set against a tragic maritime disaster." },
    { emoji: "🧙‍♂️⚡", phrase: "Harry Potter", hint: "A young boy discovers his magical heritage and destiny." },
    { emoji: "🕵️‍♂️🔍", phrase: "Sherlock Holmes", hint: "A brilliant detective solving intricate mysteries." },
    { emoji: "👽🌌", phrase: "Avatar", hint: "A visually stunning journey to an alien world with deep themes." },
    { emoji: "🧛‍♂️🧛‍♀️", phrase: "Twilight", hint: "A forbidden love story that transcends the mortal realm." },
    { emoji: "🏞️🧗‍♂️", phrase: "Into the Wild", hint: "A quest for freedom and self-discovery in nature." },
    { emoji: "👨‍🚀🌕", phrase: "First Man", hint: "A gripping portrayal of humanity's first steps on the moon." },
    { emoji: "🐉🔥", phrase: "How to Train Your Dragon", hint: "An unexpected friendship between a boy and a mythical creature." },
    { emoji: "🦸‍♂️🦸‍♀️", phrase: "The Avengers", hint: "A diverse group of heroes uniting against a common threat." },
    { emoji: "⚔️👑", phrase: "Game of Thrones", hint: "A brutal power struggle in a fantastical realm." },
    { emoji: "👨‍🍳🍝", phrase: "Chef", hint: "A culinary journey that ignites passion and creativity." },
    { emoji: "🎃👻", phrase: "Hocus Pocus", hint: "A comedic adventure with witches and mischief." },
    { emoji: "🏰👸", phrase: "Cinderella", hint: "A tale of transformation and magic under the moonlight." },
    { emoji: "🧟‍♂️🔫", phrase: "Zombieland", hint: "A humorous take on survival in a post-apocalyptic world." },
    { emoji: "🐼🎓", phrase: "Kung Fu Panda", hint: "A clumsy hero rises to greatness in martial arts." },
    { emoji: "🎤🎶", phrase: "A Star is Born", hint: "A poignant exploration of love and ambition in the music scene." },
    { emoji: "🌪️🦁", phrase: "The Wizard of Oz", hint: "A fantastical journey to find one's true home." },
    { emoji: "🦸‍♂️🕷️", phrase: "Spider-Man", hint: "A high-flying hero grappling with responsibility and power." },
    { emoji: "💼👨‍⚖️", phrase: "A Few Good Men", hint: "A courtroom drama with moral dilemmas and intense confrontations." },
    { emoji: "🎩🐰", phrase: "Alice in Wonderland", hint: "A whimsical journey through a nonsensical world." },
    { emoji: "🐉🏰", phrase: "Shrek", hint: "A fairy tale turned upside down with humor and heart." },
    { emoji: "👨‍👩‍👧‍👦🏖️", phrase: "The Incredibles", hint: "A family of superheroes navigating everyday life and villainy." },
    { emoji: "🎬💔", phrase: "La La Land", hint: "A bittersweet love story set against a backdrop of dreams and music." },
    { emoji: "🌍🚀", phrase: "Interstellar", hint: "A mind-bending journey through space and time for survival." },
    { emoji: "🧙‍♂️⚔️", phrase: "The Lord of the Rings", hint: "An epic quest to destroy a powerful artifact." },
    { emoji: "🦁👑", phrase: "The Lion King", hint: "A tale of legacy, loss, and redemption in the wild." },
    { emoji: "🔫👮‍♂️", phrase: "Die Hard", hint: "A lone cop battles terrorists in a high-stakes hostage situation." },
    { emoji: "🧟‍♀️🏃‍♂️", phrase: "World War Z", hint: "A global crisis unfolds as humanity fights for survival." },
    { emoji: "🎉🍾", phrase: "The Great Gatsby", hint: "A lavish portrayal of ambition and tragedy in the Roaring Twenties." },
    { emoji: "🕷️🕸️", phrase: "Spider-Man", hint: "A young hero learns the weight of his powers." },
    { emoji: "🦄🌈", phrase: "The Last Unicorn", hint: "A magical quest to find lost beauty in the world." },
    { emoji: "🐻🍯", phrase: "Winnie the Pooh", hint: "Heartwarming adventures in a beloved children's classic." },
    { emoji: "👽🧑‍🚀", phrase: "Arrival", hint: "A thought-provoking encounter with extraterrestrial beings." },
    { emoji: "🎭👨‍🎤", phrase: "Bohemian Rhapsody", hint: "The rise and fall of a legendary rock band." },
    { emoji: "🔥🦅", phrase: "The Hunger Games", hint: "A dystopian tale of survival and rebellion." },
    { emoji: "🎣🐟", phrase: "A River Runs Through It", hint: "A poignant reflection on family and nature." },
    { emoji: "🧞‍♂️🕌", phrase: "Aladdin", hint: "A tale of magic, adventure, and self-discovery." },
    { emoji: "🏎️💨", phrase: "Fast & Furious", hint: "High-octane thrills and adrenaline-fueled heists." },
    { emoji: "👩‍🎤🎤", phrase: "Rocketman", hint: "A musical journey through the life of a pop icon." },
    { emoji: "🏴‍☠️🏝️", phrase: "Pirates of the Caribbean", hint: "A swashbuckling adventure filled with treasure and curses." },
    { emoji: "🎨🖌️", phrase: "Pollock", hint: "The tumultuous life of a groundbreaking artist." },
    { emoji: "🐶🐾", phrase: "Lady and the Tramp", hint: "A love story that transcends social boundaries." },
    { emoji: "🐉🧙‍♂️", phrase: "Dragonheart", hint: "A tale of honor and friendship between man and dragon." },
    { emoji: "🚀🌌", phrase: "Gravity", hint: "A gripping survival story in the vastness of space." },
    { emoji: "🎤👩‍🎤", phrase: "Pitch Perfect", hint: "A competitive musical journey filled with humor." },
    { emoji: "🎡🎠", phrase: "The Greatest Showman", hint: "A celebration of uniqueness and ambition." },
    { emoji: "🧜‍♀️🌊", phrase: "The Little Mermaid", hint: "A quest for love and identity beneath the sea." },
    { emoji: "🏹🎯", phrase: "The Hunger Games", hint: "A fierce competition for survival and freedom." },
    { emoji: "🎉👰", phrase: "Wedding Crashers", hint: "A comedic exploration of love and chaos at weddings." },
    { emoji: "🥋👊", phrase: "Karate Kid", hint: "The journey of a young boy learning discipline and strength." },
    { emoji: "🏆⚽", phrase: "The Blind Side", hint: "An inspiring true story of sports and family." },
    { emoji: "🌌👽", phrase: "Contact", hint: "A profound exploration of humanity's place in the universe." },
    { emoji: "🧟‍♂️👨‍👩‍👦", phrase: "The Walking Dead", hint: "A gripping tale of survival in a zombie-infested world." },
    { emoji: "🛡️⚔️", phrase: "Gladiator", hint: "An epic tale of betrayal and revenge in ancient Rome." }
  ],
  food: [
    { emoji: "🌭🍔", phrase: "Hotdog", hint: "A popular street food often enjoyed at BBQs, usually paired with burgers." },
    { emoji: "🌻🌞", phrase: "Sunflower", hint: "A tall, bright flower that follows the sun throughout the day." },
    { emoji: "🍍🍹", phrase: "Pineapple", hint: "A tropical fruit often associated with summer drinks." },
    { emoji: "🥤🥛", phrase: "Milkshake", hint: "A creamy, blended beverage often made with ice cream and milk." },
    { emoji: "🍫☕️", phrase: "Hot Chocolate", hint: "A warm, sweet drink made with cocoa, perfect for cold days." },
    { emoji: "🥞🍯", phrase: "Pancake", hint: "A breakfast staple, often served with syrup and butter." },
    { emoji: "🧻🚽", phrase: "Toilet Paper", hint: "An essential bathroom item, especially during emergencies!" },
    { emoji: "🧅🍟", phrase: "Onion Rings", hint: "A fried snack often served as a side to burgers, made from a vegetable with layers." },
    { emoji: "🍉🍽️", phrase: "Watermelon", hint: "A refreshing, juicy summer fruit with a green rind and red flesh." },
    { emoji: "🍠🥔", phrase: "Sweet Potato", hint: "A root vegetable with a sweet flavor, often used in pies and casseroles." },
    { emoji: "🧁🎂", phrase: "Cupcake", hint: "A small, single-serving dessert, often frosted and decorated." },
    { emoji: "🥜🍯", phrase: "Peanut Butter", hint: "A creamy or crunchy spread made from ground nuts." },
    { emoji: "🍰🧀", phrase: "Cheesecake", hint: "A rich dessert made from soft cheese, often served with a crust." },
    { emoji: "🥤🌶️", phrase: "Dr Pepper", hint: "A fizzy drink with a blend of 23 unique flavors, often spiced with a little kick." },
    { emoji: "🍕🏠", phrase: "Pizza Hut", hint: "A well-known chain where you can order a slice or a whole pie." },
    { emoji: "🍔🍟", phrase: "Burger and Fries", hint: "A classic fast food combo, often enjoyed with ketchup." },
    { emoji: "🍇🍞", phrase: "Grapes and Bread", hint: "A simple snack or part of a Mediterranean meal." },
    { emoji: "🍳🥓", phrase: "Bacon and Eggs", hint: "A classic breakfast duo, often served sunny-side up." },
    { emoji: "🥐☕️", phrase: "Croissant and Coffee", hint: "A light, flaky pastry, often paired with a hot drink for breakfast." },
    { emoji: "🍤🍚", phrase: "Shrimp and Rice", hint: "A seafood dish, often found in sushi or stir fry." },
    { emoji: "🌮🌶️", phrase: "Taco and Chili Pepper", hint: "A popular Mexican dish, filled with spicy ingredients." },
    { emoji: "🍦🍒", phrase: "Ice Cream and Cherry", hint: "A frozen dessert, often topped with fruit or sprinkles." },
    { emoji: "🍔🧀", phrase: "Cheeseburger", hint: "A burger topped with a slice of melted cheese." },
    { emoji: "🍣🍶", phrase: "Sushi and Sake", hint: "A traditional Japanese dish, often paired with rice wine." },
    { emoji: "🍏🥗", phrase: "Apple and Salad", hint: "A healthy mix of greens and fruit, perfect for a light meal." },
    { emoji: "🍞🍯", phrase: "Bread and Honey", hint: "A sweet and simple snack, often enjoyed for breakfast." },
    { emoji: "🍝🍷", phrase: "Spaghetti and Wine", hint: "A classic Italian dinner, often served with garlic bread." },
    { emoji: "🍗🥔", phrase: "Chicken and Potatoes", hint: "A hearty meal, often roasted or fried." },
    { emoji: "🍪🥛", phrase: "Cookie and Milk", hint: "A sweet treat, perfect for dunking!" },
    { emoji: "🌯🥑", phrase: "Burrito and Avocado", hint: "A Mexican wrap filled with rice, beans, and often guacamole." },
    { emoji: "🍓🍰", phrase: "Strawberry Shortcake", hint: "A dessert made with fresh berries and layers of cake and cream." },
    { emoji: "🍇🍷", phrase: "Grapes and Wine", hint: "A fruit that’s transformed into a popular beverage for celebrations." },
    { emoji: "🧀🍖", phrase: "Cheese and Ham", hint: "A savory pairing, often found in sandwiches or on charcuterie boards." },
    { emoji: "🥩🍽️", phrase: "Steak Dinner", hint: "A hearty meal, usually paired with potatoes or vegetables." },
    { emoji: "🥕🥦", phrase: "Carrot and Broccoli", hint: "A healthy mix of vegetables, perfect for a side dish or snack." }
  ],
  animals: [
    { emoji: "🐻❄️", phrase: "Snowbear", "hint": "This majestic creature roams the Arctic and is often depicted as a symbol of climate change." },
    { emoji: "🐴🌊", phrase: "Seahorse", "hint": "This aquatic animal has a horse-like appearance and is known for its unusual reproductive role." },
    { emoji: "🐒🍌", phrase: "Monkey", "hint": "This intelligent animal is often associated with playful behavior and is a common subject in folklore." },
    { emoji: "🪸🌊", phrase: "Jellyfish", "hint": "This ethereal marine organism is known for its pulsating movement and can deliver a painful sting." },
    { emoji: "🦜💖", phrase: "Lovebird", "hint": "This affectionate avian species is often seen in pairs and symbolizes devotion in relationships." },
    { emoji: "🐜🦸‍♂️", phrase: "Ant Man", "hint": "This fictional character can harness the abilities of a tiny insect and is part of a larger superhero universe." },
    { emoji: "🦁👑", phrase: "Lion King", "hint": "This iconic figure represents strength and leadership in a narrative that explores the circle of life." }
  ],
  professions: [
    { emoji: "🩺💊🏥", phrase: "Doctor", "hint": "This professional often wears a white coat and helps patients recover." },
    { emoji: "📓🔍📖", phrase: "Teacher", "hint": "This individual shapes minds and often grades papers." },
    { emoji: "⚙️📏🔩", phrase: "Engineer", "hint": "Known for building things, this person often works with blueprints." },
    { emoji: "🍽️🔪🔥", phrase: "Chef", "hint": "This expert creates culinary masterpieces, often with a toque on their head." },
    { emoji: "🎭🖍️🎨", phrase: "Artist", "hint": "This creative soul often expresses emotions through various mediums." },
    { emoji: "🚒🔥🧯", phrase: "Firefighter", "hint": "This brave individual responds to emergencies and often works in teams." },
    { emoji: "🚔🔦👮‍♂️", phrase: "Police Officer", "hint": "This guardian of the law often patrols neighborhoods to ensure safety." },
    { emoji: "🧬🔬📊", phrase: "Scientist", "hint": "This profession involves conducting experiments and analyzing results." },
    { emoji: "💉🩹👩‍⚕️", phrase: "Nurse", "hint": "This caring professional often assists in surgeries and provides patient care." },
    { emoji: "🎼🎷🎤", phrase: "Musician", "hint": "This performer may play in bands or orchestras, creating melodies." },
    { emoji: "🛫✈️🌍", phrase: "Pilot", "hint": "This individual navigates the skies and may work for airlines or private companies." },
    { emoji: "📜🖋️📖", phrase: "Writer", "hint": "This person crafts stories, articles, or novels, often working alone." },
    { emoji: "📸🌄🖼️", phrase: "Photographer", "hint": "This artist captures moments in time, often using a camera." },
    { emoji: "🧾💰📈", phrase: "Accountant", "hint": "This professional often crunches numbers and prepares tax returns." },
    { emoji: "🐾🐕🩺", phrase: "Veterinarian", "hint": "This doctor cares for animals and often works in clinics or zoos." }
  ],
  places: [
    { emojis: '🏰🌳', phrase: 'Castle Garden', hint: "A majestic area often filled with flowers and greenery surrounding a historical fortress." },
    { emojis: '🏖️🌊', phrase: 'Beach Resort', hint: "A luxurious getaway by the sea, perfect for sunbathing and relaxation." },
    { emojis: '🏙️🌆', phrase: 'City Skyline', hint: "A breathtaking view showcasing tall buildings against the backdrop of a sunset." },
    { emojis: '🏞️🌄', phrase: 'National Park', hint: "A protected area known for its stunning natural beauty and diverse wildlife." },
    { emojis: '🕌🌙', phrase: 'Mosque at Night', hint: "A spiritual site illuminated under the moonlight, often featuring intricate architecture." },
    { emojis: '🏛️📚', phrase: 'Library', hint: "A quiet place filled with books, where knowledge is preserved and shared." },
    { emojis: '🏠🌾', phrase: 'Farmhouse', hint: "A cozy dwelling often found in rural areas, surrounded by fields and crops." },
    { emojis: '🏡🌼', phrase: 'Cottage Garden', hint: "A quaint home adorned with vibrant flowers, perfect for a peaceful retreat." },
    { emojis: '🚢🌅', phrase: 'Cruise Ship', hint: "A floating hotel that takes you on adventures across the ocean." },
    { emojis: '⛷️🏔️', phrase: 'Ski Resort', hint: "A winter paradise known for its slopes and cozy lodges." },
    { emojis: '🏟️⚽', phrase: 'Stadium', hint: "A large venue where fans gather to cheer for their favorite sports teams." },
    { emojis: '🌉🌆', phrase: 'Bridge View', hint: "A scenic spot offering a panoramic view of a city’s iconic bridge." },
    { emojis: '🚉🏙️', phrase: 'Train Station', hint: "A bustling hub where travelers embark on journeys to various destinations." },
    { emojis: '🏜️🌵', phrase: 'Desert Oasis', hint: "A refreshing spot in a vast arid landscape, often surrounded by palm trees." },
    { emojis: '🏭🔧', phrase: 'Factory', hint: "A place where raw materials are transformed into finished products through industrial processes." },
    { emojis: '🏬🛍️', phrase: 'Shopping Mall', hint: "A large complex filled with various stores, restaurants, and entertainment options." },
    { emojis: '🏠🌊', phrase: 'Beach House', hint: "A charming residence located by the shore, ideal for summer vacations." },
    { emojis: '🌳🏕️', phrase: 'Forest Retreat', hint: "A secluded area surrounded by trees, perfect for camping and reconnecting with nature." },
    { emojis: '🏝️🌴', phrase: 'Tropical Island', hint: "A paradise getaway known for its sandy beaches and lush vegetation." },
    { emojis: '🏢🌟', phrase: 'Corporate Office', hint: "A modern building where business deals and meetings take place." },
    { emojis: '🏕️🔥', phrase: 'Campsite', hint: "An outdoor area designated for pitching tents and enjoying nature." },
    { emojis: '🎡🎢', phrase: 'Amusement Park', hint: "A fun-filled destination featuring thrilling rides and games for all ages." },
    { emojis: '🏦💰', phrase: 'Bank', hint: "A financial institution where people manage their money and investments." },
    { emojis: '🏪🍕', phrase: 'Pizza Place', hint: "A casual eatery famous for its delicious slices and toppings." },
    { emojis: '🏺🌍', phrase: 'Museum', hint: "A cultural institution that preserves and showcases art, history, and science." },
    { emojis: '🏜️🏕️', phrase: 'Desert Camp', hint: "A temporary setup in a sandy landscape, often used for adventure trips." },
    { emojis: '⛩️🌸', phrase: 'Temple Garden', hint: "A serene space often filled with cherry blossoms, dedicated to spiritual practices." },
    { emojis: '🏭🔧', phrase: 'Industrial Area', hint: "A zone filled with factories and warehouses, crucial for manufacturing." },
    { emojis: '🏬🛍️', phrase: 'Shopping Mall', hint: "A bustling center where shoppers can find a variety of stores and eateries." },
    { emojis: '🏠🌊', phrase: 'Lakeside Cabin', hint: "A cozy retreat by the water, perfect for fishing and relaxation." },
    { emojis: '🌳🏕️', phrase: 'Nature Camp', hint: "An area designed for outdoor activities like hiking and birdwatching." },
    { emojis: '🏝️🌊', phrase: 'Island Resort', hint: "A luxurious getaway on a remote island, often featuring overwater bungalows." },
    { emojis: '🏙️🏢', phrase: 'Urban Center', hint: "A vibrant area filled with skyscrapers, shops, and cultural attractions." },
    { emojis: '🏖️🍹', phrase: 'Tropical Beach', hint: "A sun-soaked shore known for its clear waters and palm trees." },
    { emojis: '🏞️🚶‍♂️', phrase: 'Hiking Trail', hint: "A path through nature that leads adventurers to stunning vistas." },
    { emojis: '🏛️🎨', phrase: 'Art Gallery', hint: "A venue showcasing creative works, often featuring local and international artists." },
    { emojis: '🗽🌍', phrase: 'Statue of Liberty', hint: "An iconic symbol of freedom located on an island in New York Harbor." },
    { emojis: '🏰🎆', phrase: 'Castle Fireworks', hint: "A grand display of lights and colors illuminating a historic fortress." },
    { emojis: '🏖️🏄‍♂️', phrase: 'Surf Spot', hint: "A popular location for catching waves and enjoying the ocean." },
    { emojis: '🏕️🌌', phrase: 'Camping Under Stars', hint: "An experience where nature lovers sleep outdoors, gazing at the night sky." },
    { emojis: '🏢📈', phrase: 'Business District', hint: "A bustling area filled with offices and corporate headquarters." },
    { emojis: '🏟️🎤', phrase: 'Concert Venue', hint: "A large space where music lovers gather to enjoy live performances." },
    { emojis: '🗻🧗‍♀️', phrase: 'Mountain Climbing Area', hint: "A rugged terrain attracting adventurers seeking to reach new heights." },
    { emojis: '🏠🌃', phrase: 'Urban Home', hint: "A residence located in a lively city, often surrounded by nightlife." },
    { emojis: '🌌🏞️', phrase: 'Stargazing Spot', hint: "A remote area away from city lights, perfect for observing celestial wonders." },
    { emojis: '🏞️🐾', phrase: 'Wildlife Reserve', hint: "A protected area where animals roam freely in their natural habitat." },
    { emojis: '🏰🎠', phrase: 'Theme Park', hint: "A magical place filled with rides and attractions based on beloved stories." },
    { emojis: '🏙️🌉', phrase: 'Skyline Bridge', hint: "A stunning structure connecting two urban areas, offering scenic views." },
    { emojis: '🏡🌳', phrase: 'Garden Home', hint: "A residence surrounded by vibrant plants, perfect for relaxation." },
    { emojis: '🏤📮', phrase: 'Post Office', hint: "A facility where mail is sent and received, often serving the community." },
    { emojis: '🏖️🍹', phrase: 'Beach Bar', hint: "A lively spot by the shore serving refreshing drinks and snacks." },
    { emojis: '🏢🎉', phrase: 'Event Hall', hint: "A space designed for hosting celebrations, conferences, and gatherings." },
    { emojis: '🏡🏡', phrase: 'Twin Cottages', hint: "Two charming homes situated close together, often used for family retreats." },
    { emojis: '🏜️🌞', phrase: 'Sunny Desert', hint: "A vast expanse known for its bright sun and unique landscapes." },
    { emojis: '🏟️🎉', phrase: 'Festival Ground', hint: "An open area where cultural events and celebrations take place." },
    { emojis: '🏬👗', phrase: 'Fashion Boutique', hint: "A stylish store offering the latest trends and unique clothing items." },
    { emojis: '🏠🎈', phrase: 'Party House', hint: "A vibrant home often used for celebrations and gatherings." },
    { emojis: '🏕️🌲', phrase: 'Forest Camp', hint: "An outdoor area nestled among trees for camping enthusiasts." },
    { emojis: '🏢📊', phrase: 'Corporate Headquarters', hint: "The main office of a company, often featuring sleek designs." },
    { emojis: '🏖️🏝️', phrase: 'Beachside Resort', hint: "A luxurious getaway located right on the sandy shores." },
    { emojis: '🏜️🌌', phrase: 'Desert Night', hint: "An enchanting experience under the stars in a vast sandy landscape." },
    { emojis: '🏦📈', phrase: 'Financial District', hint: "A bustling area known for its banks and financial institutions." },
    { emojis: '🏪🍦', phrase: 'Ice Cream Shop', hint: "A sweet spot known for its delicious frozen treats." },
    { emojis: '🏙️🚕', phrase: 'City Streets', hint: "A lively area filled with taxis, shops, and busy pedestrians." },
    { emojis: '🏰🎇', phrase: 'Castle Fireworks', hint: "A spectacular display lighting up the night sky above a historic fortress." },
    { emojis: '🏖️🏊‍♀️', phrase: 'Swimming Beach', hint: "A popular spot for sunbathing and enjoying the water." },
    { emojis: '🏬🛒', phrase: 'Grocery Store', hint: "A convenient place for shopping for daily necessities and fresh produce." },
    { emojis: '🏛️🎉', phrase: 'Cultural Festival', hint: "An event celebrating art, music, and traditions in a historical setting." },
    { emojis: '🏢🎤', phrase: 'Performance Center', hint: "A venue designed for live shows, concerts, and theatrical performances." },
    { emojis: '🏖️🏕️', phrase: 'Beach Camping', hint: "An adventurous experience where campers set up tents by the shore." },
    { emojis: '🏞️🌲', phrase: 'Wooded Area', hint: "A serene landscape filled with trees, perfect for nature walks." },
    { emojis: '🏙️🎶', phrase: 'Music District', hint: "An area known for live music venues and vibrant nightlife." },
    { emojis: '🏡🏡', phrase: 'Twin Cottages', hint: "Two charming homes located side by side, ideal for family retreats." },
    { emojis: '🏜️🌌', phrase: 'Desert Night', hint: "A breathtaking view of the stars in a serene desert setting." },
    { emojis: '🏢🎨', phrase: 'Art Studio', hint: "A creative space where artists bring their visions to life." },
    { emojis: '🏡🌻', phrase: 'Flower Farm', hint: "A picturesque location where colorful blooms are cultivated." },
    { emojis: '🏞️🌅', phrase: 'Nature Sunset', hint: "A breathtaking view of the sun setting over natural landscapes." },
    { emojis: '🏢🍽️', phrase: 'Dining Hall', hint: "A spacious area where meals are served, often in communal settings." },
    { emojis: '🏖️🏄‍♀️', phrase: 'Surfing Beach', hint: "A prime location for catching waves and enjoying water sports." },
    { emojis: '🏜️🌵', phrase: 'Desert Adventure', hint: "An exciting trip exploring the unique landscapes of arid regions." },
    { emojis: '🏢📅', phrase: 'Conference Center', hint: "A venue designed for business meetings and large gatherings." },
    { emojis: '🏦💰', phrase: 'Investment Bank', hint: "A financial institution focused on managing large investments and assets." },
    { emojis: '🏪🍕', phrase: 'Pizzeria', hint: "A casual eatery famous for its delicious, freshly made pizzas." },
    { emojis: '🏛️📜', phrase: 'Historical Landmark', hint: "A site of significance that tells the story of the past." },
    { emojis: '🏠🔑', phrase: 'Key House', hint: "A home that symbolizes new beginnings and opportunities." },
    { emojis: '🏖️🌅', phrase: 'Sunset Beach', hint: "A picturesque shore where the sun dips below the horizon." },
    { emojis: '🏢📈', phrase: 'Corporate Office', hint: "A sleek building housing the operations of a major company." },
    { emojis: '🏞️🐾', phrase: 'Wildlife Sanctuary', hint: "A protected area dedicated to conserving animal habitats." },
    { emojis: '🏟️🎡', phrase: 'Entertainment Complex', hint: "A venue offering a mix of sports, concerts, and amusement rides." },
    { emojis: '🏬🍽️', phrase: 'Food Court', hint: "A dining area within a mall featuring various food options." },
    { emojis: '🏰🦁', phrase: 'Lion Castle', hint: "A grand fortress often associated with tales of bravery and royalty." },
    { emojis: '🏖️🏝️', phrase: 'Coastal Paradise', hint: "A dream destination known for its stunning beaches and clear waters." },
    { emojis: '🏡🌲', phrase: 'Mountain Cabin', hint: "A rustic retreat nestled in the woods, perfect for escaping the city." },
    { emojis: '🏜️🌞', phrase: 'Sunny Desert', hint: "A bright and warm landscape characterized by sand dunes and cacti." },
    { emojis: '🏢🎤', phrase: 'Music Venue', hint: "A location where artists perform live, entertaining large audiences." },
    { emojis: '🏖️🏄‍♂️', phrase: 'Surfing Spot', hint: "A popular location known for its excellent waves and beach culture." },
    { emojis: '🏞️🌳', phrase: 'Park Picnic', hint: "A delightful outing in a green space, perfect for enjoying meals outdoors." },
    { emojis: '🏢🏬', phrase: 'Commercial District', hint: "An area bustling with shops, businesses, and restaurants." },
    { emojis: '🏕️🌌', phrase: 'Camping Retreat', hint: "An escape into nature, often involving hiking and outdoor activities." },
    { emojis: '🏝️🌊', phrase: 'Island Escape', hint: "A tranquil getaway surrounded by water, ideal for relaxation." }
  ],
  entertainment: [
    { emojis: '🎤🎶', phrase: 'Concert', hint: "A live performance featuring musicians and singers entertaining an audience." },
    { emojis: '📺🍿', phrase: 'Movie Night', hint: "An evening spent watching films, often accompanied by snacks." },
    { emojis: '🎬🎥', phrase: 'Filmmaking', hint: "The process of creating movies, from script to screen." },
    { emojis: '🎮🕹️', phrase: 'Video Games', hint: "Interactive entertainment where players engage in virtual worlds." },
    { emojis: '📚🎭', phrase: 'Theater', hint: "A live performance art form involving acting, often based on scripts." },
    { emojis: '🤖🎉', phrase: 'Sci-Fi Convention', hint: "An event celebrating science fiction, featuring costumes and fan interactions." },
    { emojis: '🎨🖌️', phrase: 'Art Exhibition', hint: "A display of artistic works showcasing various styles and mediums." },
    { emojis: '🎡🎠', phrase: 'Amusement Park', hint: "A fun-filled venue featuring rides, games, and entertainment." },
    { emojis: '📻🎧', phrase: 'Podcast', hint: "A digital audio program covering various topics, available for streaming." },
    { emojis: '📖✨', phrase: 'Fantasy Novel', hint: "A book set in an imaginary world with magical elements." },
    { emojis: '🎤🎙️', phrase: 'Karaoke', hint: "A fun activity where people sing along to their favorite songs." },
    { emojis: '🎪🎭', phrase: 'Circus', hint: "A traveling show featuring acrobats, clowns, and animal acts." },
    { emojis: '🎸🤘', phrase: 'Rock Concert', hint: "A live music event featuring rock bands and energetic performances." },
    { emojis: '📼🎞️', phrase: 'Classic Film', hint: "A timeless movie that has stood the test of time, often revered by critics." },
    { emojis: '🧩🕵️‍♂️', phrase: 'Mystery Game', hint: "An interactive experience where participants solve puzzles and uncover clues." },
    { emojis: '🎉🎊', phrase: 'Festival', hint: "A large celebration featuring music, food, and various activities." },
    { emojis: '🎮👾', phrase: 'Retro Gaming', hint: "Playing classic video games from earlier generations." },
    { emojis: '🎤🏆', phrase: 'Singing Competition', hint: "A contest where vocalists showcase their talents for a prize." },
    { emojis: '🎭🎟️', phrase: 'Broadway Show', hint: "A theatrical performance held in New York's famous theater district." },
    { emojis: '🎧🎵', phrase: 'Music Playlist', hint: "A curated selection of songs for listening enjoyment." },
    { emojis: '🍿🎬', phrase: 'Film Festival', hint: "An event showcasing a variety of films, often with awards." },
    { emojis: '🎮🖥️', phrase: 'Esports', hint: "Competitive gaming where players compete in organized tournaments." },
    { emojis: '📺🎤', phrase: 'Talk Show', hint: "A television program featuring interviews and discussions with guests." },
    { emojis: '🎸🎤', phrase: 'Open Mic Night', hint: "An event where performers showcase their talents in an informal setting." },
    { emojis: '🎨🎉', phrase: 'Art Fair', hint: "An event where artists display and sell their artwork." },
    { emojis: '🎤🕺', phrase: 'Dance Party', hint: "A social gathering centered around dancing and music." },
    { emojis: '🦸‍♂️🎬', phrase: 'Superhero Movie', hint: "A film featuring characters with extraordinary powers." },
    { emojis: '📖🎬', phrase: 'Book Adaptation', hint: "A film or series based on a literary work." },
    { emojis: '🎧🎼', phrase: 'Music Album', hint: "A collection of songs released by an artist or band." },
    { emojis: '🎤🎵', phrase: 'Musical', hint: "A theatrical performance that combines songs, spoken dialogue, and dance." },
    { emojis: '🎭📜', phrase: 'Classic Play', hint: "A revered stage production that has been performed for generations." },
    { emojis: '🎹🎶', phrase: 'Piano Recital', hint: "A performance featuring a pianist playing classical or contemporary pieces." },
    { emojis: '🎮🏆', phrase: 'Gaming Tournament', hint: "A competitive event where players face off in video games." },
    { emojis: '📺🎉', phrase: 'Season Premiere', hint: "The first episode of a new season of a television show." },
    { emojis: '🎥📽️', phrase: 'Documentary', hint: "A non-fiction film that explores real-life events and subjects." },
    { emojis: '🖼️🎨', phrase: 'Art Class', hint: "An educational session focused on teaching various artistic techniques." },
    { emojis: '🎬🌟', phrase: 'Blockbuster', hint: "A highly successful film that draws large audiences." },
    { emojis: '🎸🎤', phrase: 'Live Band', hint: "A group of musicians performing together in front of an audience." },
    { emojis: '🎤🎧', phrase: 'Music Awards', hint: "An event recognizing outstanding achievements in the music industry." },
    { emojis: '📖🎤', phrase: 'Author Reading', hint: "An event where writers read excerpts from their works." },
    { emojis: '🎪🎉', phrase: 'Carnival', hint: "A festive event featuring rides, games, and entertainment." },
    { emojis: '🎭🎤', phrase: 'Improv Show', hint: "A performance where actors create scenes spontaneously." },
    { emojis: '🎮🧙‍♂️', phrase: 'Fantasy Game', hint: "A game set in an imaginary world with magical elements." },
    { emojis: '📚🎥', phrase: 'Film Adaptation', hint: "A movie based on a book or literary work." },
    { emojis: '🎧🎤', phrase: 'Voice Acting', hint: "Providing voices for animated characters in films or video games." },
    { emojis: '🎬🌍', phrase: 'World Cinema', hint: "Films produced outside of Hollywood, showcasing diverse cultures." },
    { emojis: '🎉🎭', phrase: 'Masquerade Ball', hint: "A formal dance where attendees wear masks and costumes." },
    { emojis: '🎤🏆', phrase: 'Talent Show', hint: "An event where individuals showcase their unique skills." },
    { emojis: '🎨🖼️', phrase: 'Art Gallery Opening', hint: "The launch event for a new exhibition at an art gallery." },
    { emojis: '📺🕵️‍♂️', phrase: 'Mystery Series', hint: "A television show centered around solving crimes or puzzles." },
    { emojis: '🎸🎤', phrase: 'Acoustic Concert', hint: "A live performance featuring stripped-down versions of songs." },
    { emojis: '🎬🎟️', phrase: 'Red Carpet Premiere', hint: "A glamorous event celebrating the release of a new film." },
    { emojis: '🎤🎶', phrase: 'Open Mic', hint: "An informal event where anyone can perform in front of an audience." },
    { emojis: '🎪🎡', phrase: 'Funfair', hint: "A temporary amusement event featuring rides and games." },
    { emojis: '🎬🎥', phrase: 'Short Film', hint: "A brief movie that tells a story in a limited time." },
    { emojis: '🎤🎷', phrase: 'Jazz Night', hint: "An evening dedicated to live jazz music performances." },
    { emojis: '📺📰', phrase: 'News Broadcast', hint: "A program delivering the latest news and updates." },
    { emojis: '🎭🎬', phrase: 'Film Noir', hint: "A cinematic style characterized by its dark themes and moral ambiguity." },
    { emojis: '🎤💃', phrase: 'Dance Competition', hint: "A contest where dancers showcase their skills for judging." },
    { emojis: '🎸🎤', phrase: 'Battle of the Bands', hint: "A competition where bands perform against each other." },
    { emojis: '📖🎬', phrase: 'Literary Festival', hint: "An event celebrating books, authors, and literature." },
    { emojis: '🎤🎼', phrase: 'Musical Theatre', hint: "A theatrical performance that incorporates music and dance." },
    { emojis: '🎨🖌️', phrase: 'Art Workshop', hint: "An interactive session focused on creating art." },
    { emojis: '🎡🎠', phrase: 'Theme Park', hint: "An amusement park with rides and attractions based on themes." },
    { emojis: '📖🎉', phrase: 'Book Launch', hint: "An event celebrating the release of a new book." },
    { emojis: '🎤🎭', phrase: 'Stage Play', hint: "A live performance presented on a theater stage." },
    { emojis: '🎼🎻', phrase: 'Orchestral Concert', hint: "A performance featuring a symphony orchestra." },
    { emojis: '🎬⭐', phrase: 'Celebrity Interview', hint: "A conversation with a famous person about their life and work." },
    { emojis: '🎤🎸', phrase: 'Open Air Concert', hint: "A live music event held outdoors." },
    { emojis: '📺🎥', phrase: 'Reality Show', hint: "A television program documenting real-life situations and people." },
    { emojis: '🎨🖌️', phrase: 'Art Class', hint: "A lesson focused on teaching artistic techniques." },
    { emojis: '🎤🎹', phrase: 'Piano Bar', hint: "A venue where live piano music accompanies drinks and socializing." },
    { emojis: '📖🎬', phrase: 'Screenplay', hint: "A written script for a film or television show." },
    { emojis: '🎸🎤', phrase: 'Music Festival', hint: "A multi-day event featuring various artists and bands." },
    { emojis: '🎤🎷', phrase: 'Blues Night', hint: "An evening dedicated to live blues music performances." },
    { emojis: '📺🎤', phrase: 'Reality Competition', hint: "A show where contestants compete in various challenges." },
    { emojis: '🎭🌟', phrase: 'Star-Studded Event', hint: "A glamorous gathering featuring numerous celebrities." },
    { emojis: '🎬🎥', phrase: 'Film School', hint: "An educational institution focusing on teaching filmmaking." },
    { emojis: '🎤🎶', phrase: 'Vocal Performance', hint: "A showcase of singing talent, often in front of an audience." },
    { emojis: '📖🎭', phrase: 'Literary Adaptation', hint: "A stage production based on a book or literary work." },
    { emojis: '🎬🎉', phrase: 'Film Release', hint: "The debut of a new movie in theaters." },
    { emojis: '🎤🎶', phrase: 'Choral Performance', hint: "A concert featuring a choir singing together." },
    { emojis: '📖🎤', phrase: 'Author Interview', hint: "A discussion with a writer about their works and inspiration." },
    { emojis: '🎭🎤', phrase: 'Musical Performance', hint: "A show combining music, singing, and acting." },
    { emojis: '🖼️🎨', phrase: 'Art Installation', hint: "A three-dimensional work of art designed to transform a space." },
    { emojis: '🎬🎭', phrase: 'Stage Production', hint: "A live performance presented on a theater stage." },
    { emojis: '🎤🎸', phrase: 'Rock Festival', hint: "A large outdoor event featuring rock music performances." },
    { emojis: '📺🎤', phrase: 'Late Night Show', hint: "A television program featuring celebrity interviews and comedy." },
    { emojis: '🎪🎉', phrase: 'Circus Performance', hint: "A show featuring acrobats, clowns, and various acts." },
    { emojis: '🎤🎵', phrase: 'Singing Lesson', hint: "An instructional session focused on improving vocal skills." },
    { emojis: '🎬🎥', phrase: 'Film Production', hint: "The process of making a movie from start to finish." },
    { emojis: '🎤🎶', phrase: 'Battle of the Voices', hint: "A competition showcasing vocal talent among contestants." },
    { emojis: '📖🎬', phrase: 'Book to Screen', hint: "The adaptation of a literary work into a film." },
    { emojis: '🎭🎤', phrase: 'Theatrical Performance', hint: "A live show featuring actors performing a scripted play." },
    { emojis: '🎸🎷', phrase: 'Jam Session', hint: "An informal gathering of musicians playing together." },
    { emojis: '📺🎤', phrase: 'Celebrity Roast', hint: "A comedic event where a celebrity is humorously criticized." },
    { emojis: '🎬🌟', phrase: 'Hollywood Premiere', hint: "The exclusive debut of a film in the entertainment capital." },
    { emojis: '🎤🎹', phrase: 'Piano Performance', hint: "A concert featuring a pianist playing a variety of pieces." },
    { emojis: '🎪🎡', phrase: 'Carnival Games', hint: "Fun activities and games typically found at fairs." },
    { emojis: '🎬🎥', phrase: 'Cinematic Experience', hint: "The overall enjoyment of watching films in a theater." }
  ]
};

export const emojiCategories = [
  'animals',
  'food',
  'movies',
  'places',
  'entertainment',
  'professions',
]
